### ISSUE TITLE
Bug/Closing closing app popup is closing app

### ISSUE THREAD

**Issue by Mariusz112358** [Justyna-JustCode/Resto#8]
As in title :) It should instead close popup not the app

**Comment by Justyna-JustCode** [comment]
**For further analysis**
It's about the popup which warns about the appilcation to about be hidden into the system tray.
![obraz](https://user-images.githubusercontent.com/21989150/121694801-be4f3a80-caca-11eb-96e3-aa4723278bf2.png)
